### ISSUE TITLE
SEGFAULT - windows port

### ISSUE THREAD

**Issue by filipwasil** [filipwasil/fillwave-waveracer#3]
#0  0x6fc5e26c in libstdc++-6!_ZNKSs7_M_dataEv () from C:\MinGW\bin\libstdc++-6.dll
#1  0x6fc5e1a3 in libstdc++-6!_ZNKSs6_M_repEv () from C:\MinGW\bin\libstdc++-6.dll
#2  0x6fc836bc in libstdc++-6!_ZNSs6assignERKSs () from C:\MinGW\bin\libstdc++-6.dll
#3  0x6fc854c9 in libstdc++-6!_ZNSsaSERKSs () from C:\MinGW\bin\libstdc++-6.dll
#4  0x01542b2a in fillwave::models::Text::editString (this=0x0, text=...)
    at E:\Projects\fillwave-waveracer\ext\fillwave\src\models\Text.cpp:82
#5  0x014f7f32 in fillwave::actions::FPSCallback::perform (this=0x5f8af30, engine=0x5f82e08, event=0x29fdc8)
    at E:\Projects\fillwave-waveracer\ext\fillwave\src\actions\engine_callbacks\FPSCallback.cpp:30
#6  0x015b2c23 in fillwave::Engine::runCallbacks(std::vector<fillwave::actions::EngineCallback*, std::allocator<fillwave::actions::EngineCallback*> >&, fillwave::actions::EventType*)::{lambda(fillwave::actions::EngineCallback*)#1}::operator()(fillwave::actions::EngineCallback*) const (__closure=0x29fd68, e=0x5f8af30)
    at E:\Projects\fillwave-waveracer\ext\fillwave\src\Fillwave.cpp:800
#7  0x015b1117 in std::for_each<__gnu_cxx::__normal_iterator<fillwave::actions::EngineCallback**, std::vector<fillwave::actions::EngineCallback*, std::allocator<fillwave::actions::EngineCallback*> > >, fillwave::Engine::runCallbacks(std::vector<fillwave::actions::EngineCallback*, std::allocator<fillwave::actions::EngineCallback*> >&, fillwave::actions::EventType*)::{lambda(fillwave::actions::EngineCallback*)#1}>(__gnu_cxx::__normal_iterator<fillwave::actions::EngineCallback**, std::vector<fillwave::actions::EngineCallback*, std::allocator<fillwave::actions::EngineCallback*> > >, fillwave::Engine::runCallbacks(std::vector<fillwave::actions::EngineCallback*, std::allocator<fillwave::actions::EngineCallback*> >&, fillwave::actions::EventType*)::{lambda(fillwave::actions::EngineCallback*)#1}, fillwave::Engine::runCallbacks(std::vector<fillwave::actions::EngineCallback*, std::allocator<fillwave::actions::EngineCallback*> >&, fillwave::actions::EventType*)::{lambda(fillwave::actions::EngineCallback*)#1}) (__first=..., __last=..., __f=...)
    at c:/mingw/lib/gcc/mingw32/4.8.1/include/c++/bits/stl_algo.h:4440
#8  0x01569b96 in fillwave::Engine::runCallbacks (this=0x5f82e08, callbacks=..., event=0x29fdc8)
    at E:\Projects\fillwave-waveracer\ext\fillwave\src\Fillwave.cpp:800
#9  0x01569b0d in fillwave::Engine::evaluateTime (this=0x5f82e08, timeExpiredInSeconds=0.0157504082)
    at E:\Projects\fillwave-waveracer\ext\fillwave\src\Fillwave.cpp:594
#10 0x0156e8b5 in fillwave::Engine::drawScene (this=0x5f82e08, time=0.0157504082)
    at E:\Projects\fillwave-waveracer\ext\fillwave\src\Fillwave.cpp:104
#11 0x014f2c28 in fillwave::Engine::draw (this=0x5f82e08, time=0.0157504082)
    at E:\Projects\fillwave-waveracer\ext\fillwave\src\Fillwave.cpp:227
#12 0x00405d75 in Context::render (this=0x60c1768) at E:\Projects\fillwave-waveracer\src\context.cpp:137
#13 0x00401fc5 in App::App (this=0x29ff18, argc=1, argv=0x60c4a08) at E:\Projects\fillwave-waveracer\src\App.cpp:19
#14 0x0040bb33 in main (argc=1, argv=0x60c4a08) at E:\Projects\fillwave-waveracer\src\main.cpp:24

**Comment by filipwasil** [comment]
Added more appropriate Error message when TTF font not present whech choosing FPS counter font.
